name: CD (main → production)
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
env:
  PACKAGE_PATH: '.'
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps & quick tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pytest -q || echo "No tests found."
      - name: Create ZIP package
        run: zip -r app.zip ${{ env.PACKAGE_PATH }} -x ".git/*" ".github/*" "__pycache__/*"
      - name: Upload artifact (always)
        uses: actions/upload-artifact@v4
        with:
          name: app-package-main
          path: app.zip
  deploy:
    runs-on: ubuntu-latest
    needs: package
    if: ${{ secrets.AZURE_WEBAPP_NAME != '' && secrets.AZURE_PUBLISH_PROFILE != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: app-package-main
          path: .
      - name: Deploy to Azure Web App (prod)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: app.zip
