name: CD (main → production)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  PACKAGE_PATH: '.'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests (gate)
        run: pytest -q

      - name: Create ZIP package
        run: |
          zip -r app.zip ${{ env.PACKAGE_PATH }} -x ".git/*" ".github/*" "__pycache__/*"

      - name: Deploy to Azure Web App (prod)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: app.zip
